#include "gtest/gtest.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <set>
#include <vector>
#include <list>

//------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/linked_list_functions/linked_list_functions.h"



//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

using namespace std;

bool basic_test(bool debug = false)
{
  node<int>* head = nullptr;
  node<int>* marker;

  _insert_head(head, 99);
  marker = head;

  _insert_after(head, head, 77);
  _insert_after(head, head, 88);
  
  marker = marker->_next->_next;
  _insert_after(head, marker, 55);

  marker = marker->_next;
  _insert_before(head, marker, 66);

  _print_list(head);
  cout << "Inserted: " << _previous_node(head, marker)->_item << endl;

  cout << "Deleted: " << _delete_node(head, marker) << endl;
  _print_list(head);

  cout << "\n\n-------- DONE ---------\n\n" << endl;
  return true;
}


//Lord help me! 
bool debug = false;

TEST(BASIC_TEST, BasicTest)
{
  bool success = basic_test(debug);
  EXPECT_EQ(success, true);
}


int main(int argc, char **argv)
{
  if (argc>1){
    debug = argv[1][0]=='t';
  }
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running basic_test.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}


/*
13_00_linked_list_functions git:(master)  😊 $> tree includes
includes
├── linked_list_functions
│   └── linked_list_functions.h
└── node
    └── node.h
2 directories, 2 files
13_00_linked_list_functions git:(master)  😊 $> ./build/bin/basic_test
----------running basic_test.cpp---------
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BASIC_TEST
[ RUN      ] BASIC_TEST.BasicTest
[99]->[88]->[77]->[66]->[55]->|||
Inserted: 66
Deleted: 55
[99]->[88]->[77]->[66]->|||

-------- DONE ---------


[       OK ] BASIC_TEST.BasicTest (1 ms)
[----------] 1 test from BASIC_TEST (1 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 1 test.
*/
